//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSpa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int id_appointments { get; set; }
        public decimal price { get; set; }
        public System.DateTime data_appointment { get; set; }
        public System.TimeSpan time_appointment { get; set; }
        public int id_client { get; set; }
        public int id_service { get; set; }
        public int id_master { get; set; }
        public int id_pet { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual Pets Pets { get; set; }
        public virtual Services Services { get; set; }
    }
}
