//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSpa.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetSpaEntities : DbContext
    {
        public PetSpaEntities()
            : base("name=PetSpaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ServicePrices> ServicePrices { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeightCategories> WeightCategories { get; set; }
    }
}
