//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSpa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrices
    {
        public int id_service_price { get; set; }
        public Nullable<int> id_service { get; set; }
        public Nullable<int> id_weight_category { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual WeightCategories WeightCategories { get; set; }
    }
}
