//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSpa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeightCategories()
        {
            this.ServicePrices = new HashSet<ServicePrices>();
        }
    
        public int id_weight_category { get; set; }
        public Nullable<decimal> min_weight { get; set; }
        public Nullable<decimal> max_weight { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePrices> ServicePrices { get; set; }
    }
}
